# Service Configuration
server:
  port: ${SERVICE_PORT:8086}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  application:
    name: search-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    discovery:
      enabled: ${DISCOVERY_ENABLED:true}
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: ${CONSUL_DISCOVERY_ENABLED:true}
        service-name: ${spring.application.name}
        health-check-path: /api/v1/health
        health-check-interval: 10s
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

# Service Configuration
search-service:
  service:
    name: ${SERVICE_NAME:search-service}
    version: ${SERVICE_VERSION:1.0.0}
    description: ${SERVICE_DESCRIPTION:Unified search service providing cross-service search capabilities}
    api:
      base-path: ${API_BASE_PATH:/api/v1/search}
      cache-base-path: ${API_CACHE_BASE_PATH:/api/v1/cache}
      health-base-path: ${API_HEALTH_BASE_PATH:/api/v1/health}
      version: ${API_VERSION:v1}
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
        allowed-headers: ${CORS_ALLOWED_HEADERS:*}
        max-age: ${CORS_MAX_AGE:3600}
      pagination:
        default-page: ${PAGINATION_DEFAULT_PAGE:0}
        default-page-size: ${PAGINATION_DEFAULT_PAGE_SIZE:10}
        max-page-size: ${PAGINATION_MAX_PAGE_SIZE:100}
        default-sort-field: ${PAGINATION_DEFAULT_SORT_FIELD:relevanceScore}
        default-sort-direction: ${PAGINATION_DEFAULT_SORT_DIRECTION:DESC}

# API Documentation
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /api-docs
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html