device-service:
  observability:
    metrics:
      enabled: ${DEVICE_SERVICE_OBSERVABILITY_METRICS_ENABLED:true}
      export-interval: ${DEVICE_SERVICE_OBSERVABILITY_METRICS_EXPORT_INTERVAL:60}
      include-jvm-metrics: ${DEVICE_SERVICE_OBSERVABILITY_METRICS_INCLUDE_JVM_METRICS:true}
      include-system-metrics: ${DEVICE_SERVICE_OBSERVABILITY_METRICS_INCLUDE_SYSTEM_METRICS:true}
      percentiles: ${DEVICE_SERVICE_OBSERVABILITY_METRICS_PERCENTILES:0.5,0.75,0.95,0.99}
    tracing:
      enabled: ${DEVICE_SERVICE_OBSERVABILITY_TRACING_ENABLED:true}
      sampling-probability: ${DEVICE_SERVICE_OBSERVABILITY_TRACING_SAMPLING_PROBABILITY:0.1}
      service-name: ${DEVICE_SERVICE_OBSERVABILITY_TRACING_SERVICE_NAME:${spring.application.name:device-service}}
      include-request-headers: ${DEVICE_SERVICE_OBSERVABILITY_TRACING_INCLUDE_REQUEST_HEADERS:false}
      include-response-headers: ${DEVICE_SERVICE_OBSERVABILITY_TRACING_INCLUDE_RESPONSE_HEADERS:false}
    logging:
      structured-logging: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_STRUCTURED_LOGGING:true}
      include-correlation-id: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_INCLUDE_CORRELATION_ID:true}
      include-trace-id: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_INCLUDE_TRACE_ID:true}
      application-level: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_APPLICATION_LEVEL:INFO}
      framework-level: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_FRAMEWORK_LEVEL:WARN}
      log-requests: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_LOG_REQUESTS:false}
      sanitize-sensitive-data: ${DEVICE_SERVICE_OBSERVABILITY_LOGGING_SANITIZE_SENSITIVE_DATA:true}