device-service:
  resilience:
    circuit-breaker:
      failure-rate-threshold: ${DEVICE_SERVICE_RESILIENCE_CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD:50}
      minimum-number-of-calls: ${DEVICE_SERVICE_RESILIENCE_CIRCUIT_BREAKER_MINIMUM_NUMBER_OF_CALLS:10}
      wait-duration-in-open-state: ${DEVICE_SERVICE_RESILIENCE_CIRCUIT_BREAKER_WAIT_DURATION_IN_OPEN_STATE:30s}
      sliding-window-size: ${DEVICE_SERVICE_RESILIENCE_CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE:20}
      enabled: ${DEVICE_SERVICE_RESILIENCE_CIRCUIT_BREAKER_ENABLED:true}
    retry:
      max-attempts: ${DEVICE_SERVICE_RESILIENCE_RETRY_MAX_ATTEMPTS:3}
      wait-duration: ${DEVICE_SERVICE_RESILIENCE_RETRY_WAIT_DURATION:1s}
      backoff-multiplier: ${DEVICE_SERVICE_RESILIENCE_RETRY_BACKOFF_MULTIPLIER:2.0}
      enabled: ${DEVICE_SERVICE_RESILIENCE_RETRY_ENABLED:true}
    timeout:
      default-timeout: ${DEVICE_SERVICE_RESILIENCE_TIMEOUT_DEFAULT_TIMEOUT:10s}
      database-timeout: ${DEVICE_SERVICE_RESILIENCE_TIMEOUT_DATABASE_TIMEOUT:5s}
      http-timeout: ${DEVICE_SERVICE_RESILIENCE_TIMEOUT_HTTP_TIMEOUT:30s}