device-service:
  thread-pool:
    event-publisher:
      core-size: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_CORE_SIZE:2}
      max-size: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_MAX_SIZE:10}
      queue-capacity: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_QUEUE_CAPACITY:500}
      thread-name-prefix: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_THREAD_NAME_PREFIX:event-publisher-}
      keep-alive-seconds: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_KEEP_ALIVE_SECONDS:60}
      await-termination-seconds: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_AWAIT_TERMINATION_SECONDS:60}
      allow-core-thread-timeout: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_ALLOW_CORE_THREAD_TIMEOUT:false}
      wait-for-tasks-to-complete-on-shutdown: ${DEVICE_SERVICE_THREAD_POOL_EVENT_PUBLISHER_WAIT_FOR_TASKS_TO_COMPLETE_ON_SHUTDOWN:true}
    default-pool:
      core-size: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_CORE_SIZE:5}
      max-size: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_MAX_SIZE:20}
      queue-capacity: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_QUEUE_CAPACITY:1000}
      thread-name-prefix: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_THREAD_NAME_PREFIX:device-async-}
      keep-alive-seconds: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_KEEP_ALIVE_SECONDS:60}
      await-termination-seconds: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_AWAIT_TERMINATION_SECONDS:60}
      allow-core-thread-timeout: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_ALLOW_CORE_THREAD_TIMEOUT:false}
      wait-for-tasks-to-complete-on-shutdown: ${DEVICE_SERVICE_THREAD_POOL_DEFAULT_POOL_WAIT_FOR_TASKS_TO_COMPLETE_ON_SHUTDOWN:true}