# Main Application Configuration for Notification Service
# This file imports all modular configuration files and contains core Spring settings

spring:
  application:
    name: notification-service
    
  # Configuration imports - modular configuration files
  config:
    import:
      - application-service.yml
      - application-kafka.yml
      - application-email.yml
      - application-templates.yml
      - application-events.yml
      - application-formatting.yml
      - application-features.yml
      - application-resilience.yml
      - application-validation.yml
      - application-thread-pool.yml
      - application-observability.yml
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:timescaledb}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:notification_user}
    password: ${SPRING_DATASOURCE_PASSWORD:notification_pass}
    driver-class-name: org.postgresql.Driver
    
    # Connection pool configuration
    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}
        jdbc:
          batch_size: ${JPA_BATCH_SIZE:25}
        order_inserts: true
        order_updates: true
    show-sql: ${JPA_SHOW_SQL:false}
    
  # Kafka configuration (basic settings, detailed in application-kafka.yml)
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:notification-service}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
  # Service discovery configuration
  cloud:
    consul:
      enabled: ${CONSUL_ENABLED:true}
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: ${CONSUL_DISCOVERY_ENABLED:true}
        instance-id: ${spring.application.name}:${server.port}:${random.value}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: ${CONSUL_HEALTH_CHECK_INTERVAL:15s}
        health-check-timeout: ${CONSUL_HEALTH_CHECK_TIMEOUT:10s}
        prefer-ip-address: ${CONSUL_PREFER_IP_ADDRESS:true}
        
  # Mail configuration (basic settings, detailed in application-email.yml)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
            required: ${MAIL_SMTP_STARTTLS_REQUIRED:true}

# Server configuration
server:
  port: ${SERVER_PORT:8083}
  
  # Graceful shutdown
  shutdown: ${SERVER_SHUTDOWN:graceful}
  
  # Error handling
  error:
    include-message: ${SERVER_ERROR_INCLUDE_MESSAGE:always}
    include-binding-errors: ${SERVER_ERROR_INCLUDE_BINDING_ERRORS:always}
    include-stacktrace: ${SERVER_ERROR_INCLUDE_STACKTRACE:on_param}
    include-exception: ${SERVER_ERROR_INCLUDE_EXCEPTION:false}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,prometheus}
      base-path: ${MANAGEMENT_BASE_PATH:/actuator}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
      probes:
        enabled: ${MANAGEMENT_HEALTH_PROBES_ENABLED:true}
    metrics:
      enabled: ${MANAGEMENT_METRICS_ENABLED:true}
    prometheus:
      enabled: ${MANAGEMENT_PROMETHEUS_ENABLED:true}
  metrics:
    export:
      prometheus:
        enabled: ${METRICS_EXPORT_PROMETHEUS_ENABLED:true}

# Default logging configuration (detailed in application-observability.yml)
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    io.thatworked.support.notification: ${LOG_LEVEL_NOTIFICATION:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:WARN}
    org.springframework.kafka: ${LOG_LEVEL_KAFKA:INFO}